### ISSUE TITLE
[Spell] [Warlock] Soul Shards (Soulburn)

### ISSUE THREAD

**Issue by Burag** [Valhalla-Gaming/Tracker#1452]
The warlock specialization (affliction) the main thing is bugged. The soul shards are automatically generating in out of combat but I cant use them for nothing.For example I can't use my Soulburn (http://www.wowhead.com/spell=74434/soulburn) .I cant cast it but I have soul shards already pls fix it as soon as possible its very important.Thx!

**Comment by Usernameisntalreadytaken** [comment]
The problem is different now.
There is literally no way to regenerate soul shards in combat anymore.

Corruption's 6% chance to get a soul shard upon ticking?
Nope.

Drain soul finishing someone off?
Nope.

Warlords season 2's 2 pieces bonus (+1 soul shard every silence/interrupt every 15 seconds)?
Nope, it doesn't give any soul shards either.

As a result of this, instead of getting stronger the longer a fight lasts through DoTs doing their work, afflictions gets considerably weaker as once all 4 soul shards are spent, you're basically useless.
Can't cast HAUNT (1 shard per cast, must have for burst/finishing off), can't cast SOULBURN:HAUNT (2 shards per cast, must have for burst), can't cast soul swap (it's bugged by the way!), can't instantly resummon pets (all pets are beyond bugged to hell and die really, really fast) mid-battle, can't cast soulburn: demonic circle: teleport (not like demonic circle: teleport works anyways, right?)...

Affliction is as broken as demonology is right now, but it's harder to notice unless you play an afflock yourself.
