### ISSUE TITLE
Arcane Mage Bug: Arcane Blast/Charge/Missiles Interaction

### ISSUE THREAD

**Issue by Gantian2** [Valhalla-Gaming/Tracker#1898]
Arcane blast consumes charges of Arcane missiles, when they should stack up to 3 times. Arcane missiles when used consumes stacks of Arcane Charge, it should refresh the duration.

**Comment by Malae1** [comment]
Ref #1512

**Comment by nuhrii** [comment]
The Arcane Blast consuming Arcane Missiles! has been fixed. Arcane Missiles is still broken, it doesn't generate a Arcane Charge on cast, it can generate a Arcane Missiles! charge each time it does damage which it shouldn't, and its consuming Arcane Charges without actually consuming them because the game still thinks you have X Arcane Charges until you reset the charges with Arcane Barrage.
http://www.wowhead.com/spell=5143
