### ISSUE TITLE
[Hunter] talents and bugs attacks

### ISSUE THREAD

**Issue by ricardoesl** [Valhalla-Gaming/Tracker#3178]
Talents:
http://www.wowhead.com/spell=118922/posthaste not working
http://www.wowhead.com/spell=109298/narrow-escape not working
http://www.wowhead.com/spell=109212/spirit-bond not working
http://www.wowhead.com/spell=109260/iron-hawk passive damage reduction effect is applied, but does not reduce the damage really
http://www.wowhead.com/spell=131894/a-murder-of-crows It applied on the target, but does not work
http://www.wowhead.com/spell=121818/stampede not working
http://www.wowhead.com/spell=162534/exotic-munitions any ammunition to throw this if applicable, but the damage in the time it takes equals 1 damage
http://www.wowhead.com/spell=152245/focusing-shot not give the 50 focus points

Gliphs
http://www.wowhead.com/spell=132106/glyph-of-liberation using separation does not give 4% of healing

Spells
http://www.wowhead.com/spell=51753/camouflage the effect of camouflage does not apply if you perform the healing, but not hide the hunter
http://www.wowhead.com/spell=53209/chimaera-shot It does no damage
http://www.wowhead.com/spell=83381/kill-command It does no damage

And finally, check the damage and attack power of the hunter as he was now reduced and its damage is far below what you owe. It can not be that having 625 item level, my dps is of 6.5k

**Comment by Moustachos** [comment]
- Posthaste was fixed in a previous update
- Narrow Escape was fixed in a previous update
- Spirit Bond will be fixed on next update
- Iron Hawk works fine
- A Murder of Crows will be fixed on next update
- Exotic Munitions was fixed in a previous update
- Chimaera Shot was fixed in a previous update
- Kill Command will be fixed on next update

So the remaining bugs listed here are:
- Focusing Shot not giving 50 Focus
- Glyph of Liberation not healing after using Disengage
- Camouflage not working

**Comment by Moustachos** [comment]
Glyph of Liberation will be fixed on next update.

**Comment by Moustachos** [comment]
Focusing Shot will properly grant 50 Focus for BM / Survival hunters on next update.

**Comment by Moustachos** [comment]
Stampede was fixed on last update, the only remaining bug is on Camouflage.
