### ISSUE TITLE
Priest problems (Shadow+Holy)

### ISSUE THREAD

**Issue by Rames312** [Valhalla-Gaming/Tracker#3244]
Glyph of Mind harvest - increases cd by 5secs but doesnt give 2 shadow orbs
Devouring Plague - does dmg but doesnt do the DoT effect or healing
Shadow Word : Death - doesnt give shadow orb
Heal and Flash Heal - they both heal for same amount but Heal has slower cast speed (i think heal should heal more than Flash Heal)

**Comment by Malae1** [comment]
The two healing spells you spoke of are near identical in healing values because this was changed in WoD. Flash heal is meant to be a more immediate quick heal and cost more, while the other regular heal is mean to be more steady heal with cheaper value. You are likely thinking of previous expansions when heal was greater heal and would heal for more than twice the amount.

**Comment by Guybrush-Hellscream** [comment]
Glyph of Mind Harvest : http://www.wowhead.com/spell=162532/glyph-of-mind-harvest
Devouring Plague : http://www.wowhead.com/spell=2944/devouring-plague
Shadow Word: Death : http://www.wowhead.com/spell=32379/shadow-word-death

**Comment by Moustachos** [comment]
All of these issues will be fixed on next update.

**Comment by Moustachos** [comment]
Ref #2266
