### ISSUE TITLE
Warlock, (Demonology) Imps replacing main pet.

### ISSUE THREAD

**Issue by Krizar73** [Valhalla-Gaming/Tracker#4607]
Main Warlock's pet disappears after Shadowbolt, Soul Fire or other abilities causing Imps to proc get casted.

**Comment by Warborn501** [comment]
I can confirm this, and its pretty annoying to say the least. I cant even play demonology anymore because of this.

**Comment by Starlords** [comment]
This is a MAJOR bug, its hard to play only with the curse-base spells (curruption and such), Warlocks need ofensive too :( ! Please fix it, or at least turn off Imps being casted while you look for the solution...

**Comment by Warloky** [comment]
I'm with this guys its been awhile and this bug is still here i really like demonology warlocks so I hope you guys can find a solution... Thanks for your hard work but we need this bug gone!

**Comment by Tregeta** [comment]
We believe the reasoning behind these pets replacing the main pets are because they are classified as companion pets instead of guardian pets (very big difference). Companion pets such as hunter pets, warlock pets, and the mage pet are considered permanent, while guardian pets such as these imps that proc off spells are on a limited time up. We hope to have this rectified as fast as possible however we still require a bit more research through our data for the particular class, long story short it should be soon!

**Comment by Warloky** [comment]
Thanks a lot for your work, is nice to see that you are doing all you can

**Comment by Tregeta** [comment]
@Usernameisalreadytaken
>When you cast "summon Infernal", it makes your current pet (a voidwalker for example) despawn.
When you try to summon a pet (a voidwalker for example) while an infernal is already summoned, the infernal despawns.
Infernals (and doomguards, and abysals, and maybe a couple other lock summons) are meant to be GUARDIANS and not PETS and therefore should not be mutually exclusive with pets.
