### ISSUE TITLE
Runic Corruption

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#4763]
http://www.wowhead.com/spell=51462/runic-corruption

I'm not sure what the issue is or is it retail like but with this talent I'm able to easily use 4 obliterates in a row AND my best "score" so far is 10 in a row.

Maybe proc chance is too high? 

Also this effect lasts for 5 seconds instead of 3.

**Comment by Tregeta** [comment]
Ref #1962

**Comment by Moustachos** [comment]
Both Runic Corruption and Runic Empowerment have a chance to proc of 1.5% per runic power spent, so let's say you're casting a Death Coil (or Frost Strike) for 40 rp cost, you got 60% chance to proc these talents, so that's pretty high and it's not a bug.

About the duration, see: http://wow.gamepedia.com/Runic_Corruption

> Patch 4.0.6 (2011-02-08): Runic Corruption procs while the aura is already active now add 3 seconds to the existing aura duration, instead of simply refreshing/overwriting the existing aura.
