### ISSUE TITLE
Weekly conquest cap

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#4770]
After one of the updates (or crashes) weekly conquest cap went down to basic amount of 1500 conquest points. Above 1550 (or 1500?) rating weekly conquest cap should increase.

![wowscrnshot_022416_200344](https://cloud.githubusercontent.com/assets/14946340/13297280/d42d3f5c-db31-11e5-8c91-e0d520b9af58.jpg)

Before update/crash I had 1900+ weekly cap.

**Comment by Egnivia** [comment]
I have increased cap. Try to play 1 game to change best rating.

**Comment by Collector-Valhalla** [comment]
So weekly conquest cap goes down to basic amount if I don't play arena for some longer time?

meh

**Comment by Egnivia** [comment]
It should be bug.. Because i have 1900cap or smth like that and im playing arenas.

**Comment by EPS1L0N** [comment]
We had to manually reset the cap this week, due to a bug that came up with the timers. I'm not sure if that has something to do with it but everything should be back to normal the next time it resets. Also, your cap is calculated based on your best rating from the previous week, so if you don't do arenas for a week it will reset to 1500- this is blizzlike
