### ISSUE TITLE
Druid Spell: Rejuvenation 

### ISSUE THREAD

**Issue by skorge1** [Valhalla-Gaming/Tracker#4924]
The issue with http://www.wowhead.com/spell=774/rejuvenation is that in restoration spec when you get the level 100 talent http://www.wowhead.com/spell=155675/germination you have to apply the spell 3 to 4 times to get the actual duration of the spell which is 23 seconds. Instead of  on the first cast and second for germination.http://www.wowhead.com/spell=157300/empowered-rejuvenation. I'm sure if you didn't have the talent you would have to apply it twice to get the actual 20 second duration.

**Comment by Moustachos** [comment]
There is no bug: initial duration of Rejuvenation is 12 seconds, and you can get:
- +3 seconds with Germination
- +3 seconds with Empowered Rejuvenation

For a total of 18 seconds (the duration you get when you first cast Rejuvenation). If you refresh it, you benefit from a mechanic called _duration overlap_.

It allows to add 30% of the initial max duration of a periodic effect to its refresh duration.

18 * 1.3 = 23.4 sec (23 because of rounding)

So everything's fine :)

**Comment by Moustachos** [comment]
Ref #2266
