### ISSUE TITLE
surge of light visual

### ISSUE THREAD

**Issue by Traveler-Valhalla** [Valhalla-Gaming/Tracker#5141]
Currently when you get a second charge of surge of light you still have only one visual effect on left side. You should get a second one on right side. Right? D:

![wowscrnshot_041916_034553](https://cloud.githubusercontent.com/assets/14946340/14625201/49080260-05e1-11e6-96b5-8945d580266d.jpg)

**Comment by Luminescent-Valhalla** [comment]
If it works the same way paladins do no it's normal for example on Pala as
ret if you proc divine storm and exorcism one takes up one side and the
other proc shows on the other as you can see from this retail screen shot
On 19 Apr 2016 2:48 a.m., "Collector" <notifications@github.com> wrote:

Currently when you get a second charge of surge of light you still have
only one visual effect on left side. You should get a second one on right
side. Right? D:

[image: wowscrnshot_041916_034553]
<https://cloud.githubusercontent.com/assets/14946340/14625201/49080260-05e1-11e6-96b5-8945d580266d.jpg>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/Valhalla-Gaming/Tracker/issues/5141>

**Comment by Tregeta** [comment]
Can confirm Collector's report, should show two if have two proc's.
