### ISSUE TITLE
Druid Glyph: Glyph of Aquatic Form

### ISSUE THREAD

**Issue by skorge1** [Valhalla-Gaming/Tracker#5434]
The issue with http://www.wowhead.com/spell=57856/glyph-of-aquatic-form is that it increases the swim speed by 34% not 50%

**Comment by carminejackal** [comment]
Aquatic Form increases swim speed by 50%. Take note that this 50% increase is of the 66.6% base swim speed, hence giving a 33.3% bonus. Thus the net effect of this form is to allow you to move at 100% normal running speed, in water.

Since this glyph uses the same wording as Aquatic Form, it's likely that it works in the same way too, making AF give a total bonus of 100% to the 66% base swim speed, and ending up at 133%.

I just checked this in Stormwind canals with patch 4.0.3a;
Swimming in caster/ normal form (67% Run Speed) = 4.72/ yards per second
Swimming in Aquatic Form no Glyph of Aquatic Form (101% Run Speed) = 7.08/ yards per second
Swimming in Aquatic Form with Glyph of Aquatic Form (135% Run Speed) = 9.44/ yards per second
Note: the increase is additive not multiplicative, or, 50 %/ 100% added to base Run Speed.

http://www.wowhead.com/item=43316/glyph-of-aquatic-form#comments
