### ISSUE TITLE
[Druid] Shifting rage

### ISSUE THREAD

**Issue by CageValhalla** [Valhalla-Gaming/Tracker#5533]
Rage resets by shifting forms while it should stay and decrease like while in bear form.

**Comment by Luminescent-Valhalla** [comment]
My findings test on retail at the time of posting this shows that this is not a bug on retails current build 

![2016-06-17_07-27-15](https://cloud.githubusercontent.com/assets/13806368/16142423/17a36282-345d-11e6-99f7-9213f68ad013.png)
![2016-06-17_07-27-20](https://cloud.githubusercontent.com/assets/13806368/16142431/1de31f7a-345d-11e6-80bb-dd55f6564079.jpg)
![2016-06-17_07-27-26](https://cloud.githubusercontent.com/assets/13806368/16142434/21ae039a-345d-11e6-85ff-81a71b2f8eb6.jpg)

Tested while in Feral spec if you were in guardian spec at the time of testing let me know and i will double check with guardian spec (Reason you able to see double wow images on screens is due to software showing previews of last screen also shows images were taken right after droping and entering form to try and replicate the issue)

**Comment by CageValhalla** [comment]
Yeah, guardian spec

**Comment by Luminescent-Valhalla** [comment]
@CageValhalla when your online can you screen your talents and glyphs for me so i can make sure i have everything the same to confirm the issue.

**Comment by CageValhalla** [comment]
[http://imgur.com/fgCBI5J](img)
[http://imgur.com/0GRPmFh](img)

**Comment by Luminescent-Valhalla** [comment]
Tested using guardian spec along with the same talents ect and my findings were still the same upon switching from bear to cat and back to bear any rage you had is reset to a value of 10 rage upon entering bear form 

100% rage bear form http://i.imgur.com/hiSEwI8.jpg
Switched to cat form instantly http://i.imgur.com/AlP4Th6.jpg
and back to bear right away http://i.imgur.com/Yzwy2Bh.jpg
