### ISSUE TITLE
MM hunter All  THAT IS WRONG SO FAR 

### ISSUE THREAD

**Issue by sean1359** [Valhalla-Gaming/Tracker#5740]
here is a list of ALL the things that i have found to be incorrect with the MM hunter right now mechanically at the moment .

1.) Kill Shot  is incorrect on this server! here is a link to how it  SHOULD  function http://www.wowhead.com/spell=157708/kill-shot    right now it is set to 20% which is fucking bullshit!
2.) trap launcher's hit box is so messed up and off  cannot accuratly trap mobs corectly  please fix!!!!

3.) when you have a pet out and you mount up your pet stays by your side! it does not disapear ! please fix this it is causeing my pets to be lost alll together is i get a companion from a quest or from trinket ( houndmaster SM) itll count it as pety and wont let me revive or re summon the pet  it will be lost forever n i will have top grab another this hasdta be fixed please!   i can record a video of me on live servers  mounting up and my pet stays just fine so i know it  should work like that .

**Comment by nuhrii** [comment]
The Kill Shot one is not the standard version, its the one that you get when you start to level in Draenor.
 Trap launcher is working as intended, I click on a trap and click where i want it to go it goes where I pointed.
 So the only real issue is Hunter Pets out while mounted. Its also good housekeeping to create multiple separate issues rather than just have a bunch in one.
