### ISSUE TITLE
[Quest] Revenge is Tasty

### ISSUE THREAD

**Issue by Braemen** [Valhalla-Gaming/Tracker#5923]
The item [Giant Kaliri Wing](http://www.wowhead.com/item=33838/giant-kaliri-wing), required for the quest [Revenge is Tasty](http://www.wowhead.com/quest=11377/revenge-is-tasty) and dropped only by [Monstrous Kaliri](http://www.wowhead.com/npc=23051/monstrous-kaliri), has never been dropped in dozens of times I have killed them.
I don't know if drop rate is ridiculously low or they never drop.
According to what wowhead says, they should have 31% of drop rate. Pretty high.

**Comment by Guybrush-VR** [comment]
Just as a heads up, Wowhead rates are not accurate because they're taking in account every people killing kaliris, not just the ones with the actual quest. 
You're still correct though since the actual drop rate is "Very High", so definitely over 50%.
Check your items here, with the search bar in the top right corner : 
http://eu.battle.net/wow/en/item/33838

**Comment by Braemen** [comment]
Yes I know, but wowhead's "31%" is more accurate than blizzard's "Very High" :smile:

**Comment by Guybrush-VR** [comment]
Well, once you get the hang of Blizzard's, you can deduce the real rates with numbers. The deduction being more accurate than Wowhead's rates. :stuck_out_tongue:
Anyway, it's still an almost guaranteed drop. :bowtie:

**Comment by Braemen** [comment]
Update: after a lot of kills I got the item

**Comment by Tregeta** [comment]
Fixed next update
