### ISSUE TITLE
Shaman Maelstorm Mechanics

### ISSUE THREAD

**Issue by Bombrick** [Valhalla-Gaming/Tracker#5941]
At level  3 you get earth shock to use it you have to be having an amount of "Maelstorm" energy you get it by casting lightning  bolt but when you cast lightning bolt you don't get maelstorm so you can't use earth shock or other spells that requires maelstorm

**Comment by GM-Pyromanic** [comment]
Issue should be fixed with the latest change log 

> 2016.5.09.070200^
Core: General Updates
• Druids will now start with their proper abilities
• Fixed Combo Points for Rogues
• Fixed Fury & Pain not properly decaying for Demon Hunters
• Fixed Mana for Mistweaver Monks
• Fixed Runic Power generation for Death Knights
• Implemented Maelstrom power for Shaman

**Comment by Bombrick** [comment]
Fixed
