### ISSUE TITLE
momentum + fel rush

### ISSUE THREAD

**Issue by Traveler-Valhalla** [Valhalla-Gaming/Tracker#6357]
**Describe the issue you're having**:
Momentum talent doesn't work with fel rush ability.
**Explain how you expect it work**:
Well I expect it to work with fel rush.
**Steps to reproduce the problem**:

1. Umm
2. take momentum talent
3. use fel rush

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=206476/momentum

**Comment by Redrian-Hellscream** [comment]
It has been fixed.. somehow.
Now Fel Rush seems to trigger momentum, but the problem is another:
Momentum at the moment gets triggered by Demon's bite, Felblade and Throw Glaive, this SHOULD NOT happen, Collector please confirm my statement about Fel Rush on your build and update the report with what I said about the other 3 abilities.

**Comment by Moustachos** [comment]
Ref #5979
