### ISSUE TITLE
90 LVL BOOST İS BUG

### ISSUE THREAD

**Issue by Furyr** [Valhalla-Gaming/Tracker#6460]
**Describe the issue you're having**:
![image](https://cloud.githubusercontent.com/assets/22060103/18397542/6c587c98-76d1-11e6-85ca-1e6aaafac635.png
HEY GUYS HELP ME I BUY BOOST BUT DONT SEND ARMOR , MOUNT , WEAPON
**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Braemen** [comment]
Man, this is not the right place to ask for help. Use issue tracker for report issues, and forum for help.
Your issue is already reported and you received an answer in [this issue comment](https://github.com/Valhalla-Gaming/Tracker/issues/6283#issuecomment-245811818).
Just follow the instructions.
Adding the same issue over and over will only make GMs' work more complicated :smile:

**Comment by Furyr** [comment]
OK TY :D :D :D :D
