### ISSUE TITLE
No Pet available

### ISSUE THREAD

**Issue by atomictweety** [Valhalla-Gaming/Tracker#6718]
**Describe the issue you're having**:

**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. My pet does not appear to my side when called, revived or after relog.
2. My pet should be by my side at all times, especially if i act upon the [Call Pet] spell. 
3. Lvl 7 Hunter, Blood Elf, Deevana, I played up until lvl 7 with no problem, i logged out. The 2nd day the pet does not reappear back to my side by any spell, nor after relogg, erasing cache or "unstuck"action.

**Links to Wowhead, YouTube, etc**:

**Comment by Traveler-Valhalla** [comment]
I'll add another example. 

As a goblin you start with a pet without a problem but when you use a portal to Orgrimmar (since their zone does not work) you'll lose your pet. Furthermore when you hit level 10 and you're able to tame a new pet it will work however it will take 2 slots (or more haven't leveled further yet) of pets.

**Comment by Moustachos** [comment]
Ref #5979
