### ISSUE TITLE
Death and Decay

### ISSUE THREAD

**Issue by GeneralCaveman** [Valhalla-Gaming/Tracker#691]
http://www.wowhead.com/spell=43265/death-and-decay

Death and Decay currently does no damage.

**Comment by KwitUrBichn** [comment]
https://github.com/HellscreamWoW/Tracker/issues/1959

**Comment by Tregeta** [comment]
Copy/Paste with additional information from @CorentinDodon

This spell have already been referenced for not doing any damages but this isn't totally true.

The targets in the area touched by Death and Decay don't take any damages because the spell actually follow the Death Knight. There isn't any animation around the caster but the targets around does take the damage of the spell.
It seems that the caster is in the center of the spell and it follows the caster for the entire duration of the spell.

In an other side the glyph of death and decay only slows the target which are in the area of the Death and Decay you have chosen to place where we can see the animation of the spell

**Comment by Moustachos** [comment]
Ref #2266
