### ISSUE TITLE
Mage Fire can't crit 

### ISSUE THREAD

**Issue by Dionox** [Valhalla-Gaming/Tracker#6973]
**Describe the issue you're having**:
Mage fire crit bugged= proc /hot-streak/= damage. Mage fire is unless now
**Explain how you expect it work**:
mage fire must crit
**Steps to reproduce the problem**:
1. do damage /the spell Fire Blast(always crit?...no)
2.  use all spell ground to the crit(never crit ) except the passive Enhanced Pyrotechnics 
can crit using fireball but can't proc Hot Streak (i'm lvl 40)

http://www.wowhead.com/spell=108853/fire-blast
http://www.wowhead.com/spell=157642/enhanced-pyrotechnics
http://www.wowhead.com/spell=195283/hot-streak

**Comment by nuhrii** [comment]
Been reported

**Comment by LordYawgmoth** [comment]
the issue is different
it  s not that the mage cant crit (with firestarter ur fireball crits always on full hp targets) but the system doesnt recognize the crit? at least u get the "u didnt crit" buff instead of the "heating up" (the first procc before hotstreak is triggered), but yes basically hotstreak is broken and makes firemage useless
