### ISSUE TITLE
Mob Damage

### ISSUE THREAD

**Issue by Atlasxyz** [Valhalla-Gaming/Tracker#7323]
**Describe the issue you're having**:
Mobs are hitting me, a level 110 druid, for 8 - 10% of my HP per AUTO ATTACK hit. They hit much much harder than they do on retail. 
**Explain how you expect it work**:
The should be hitting a fraction as hard as they do now. Fraction being 1/5th for the higher levels, about 1/3rd for the lower levels.
**Steps to reproduce the problem**:
1. Get hit by a mob your level.
   ![wowscrnshot_101916_152135](https://cloud.githubusercontent.com/assets/22627544/19534333/5d623d64-9611-11e6-8cc3-bd5d639a5c9d.jpg)
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by lavalampe77** [comment]
This issue should be marked as critical, because legion mobs aren't supposed to hit you with nearly the same meele damage a player does to them (when you imagine they dont even have their special abilities used). Their damage is 4-5 times higher then on retail and this fact totally destroys any kind of pve since months. This fact leads to an blizz-unlike experience and demotivates players to farm.

**Comment by Moustachos** [comment]
Fixed in a previous update.
