### ISSUE TITLE
pvp artifact appearance 

### ISSUE THREAD

**Issue by aetoni** [Valhalla-Gaming/Tracker#7728]
**Describe the issue you're having**: I know this issue has been reported but im reporting it again anyways because i really want to see it fixed. At prestigle lvl 1 rank 50 you get the quest wich should lead you to unlocking new artifact appearance, so you need to speak with king endwyn in stormwind but you can not because stormwind is still kinda in the past so all you can find is king varian and prince endwyn wich does not allows you to complete the quest.

**Explain how you expect it work**: get the quest from the quest item ( A royal audience) , and talk to endwyn wich gives you quest 'victors spoils' wich unlocks the pvp artifact appearance.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/quest=42978/a-royal-audience http://www.wowhead.com/quest=42978/a-royal-audience

**Comment by kmazz** [comment]
I know you are anxious to see this fixed, but it is much easier to go back and look at 1 rather than scroll through multiple of the same thing for our developers. 

Please try not to report things that have already been reported! Our dev team is working their hardest trying to get to everything. This will come soon enough just give them some time to get it right!

**Comment by GM-Pyromanic** [comment]
Duplicate report #7498

Creating another report for the same issue do not make fixes happen quicker it just slows the developers down looking for other reports for the same thing to get all the information from reports made they may need.
