### ISSUE TITLE
drain life with relic

### ISSUE THREAD

**Issue by Traveler-Valhalla** [Valhalla-Gaming/Tracker#8058]
**Describe the issue you're having**:
Something strange happened. 
I've checked Drain Life tooltip (affliction spec) before applying shadow relic (10% more healing from drain life) and it said that "heals for 195% of damage done". After adding that relic tolltip of drain life changed to "...260%...". And after relogging drain life tooltip said that it heals for "...660%...".
**Explain how you expect it work**:
I have no idea. WoWHead says that it should heal for 600% so I guess with relic it should be 610%???
**Steps to reproduce the problem**:

1. make affliction lock
2. get artifact
3. add that relic from link below

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/item=141291/shalanir-sproutling&bonus=1826
http://www.wowhead.com/spell=689/drain-life

**Comment by Traveler-Valhalla** [comment]
Just noticed: 
while running around the world drain life's tooltip says 660%
when in instance it says 258%

So it might be just visual for tooltip? No idea.

![wowscrnshot_120716_154514](https://cloud.githubusercontent.com/assets/14946340/20972229/86eb3b32-bc94-11e6-9f9f-ecec2e2e09f5.jpg)

**Comment by Tolno** [comment]
"Heals 10% more", and heals for 600% of your damage. 600 +10% = 660% of the damage done.
Going from 600 to 610% of your damage would be a increase of _1.66_%.

Second thing, 198% is normal for affliction due to the passive effect **_Secrets of the Necrolyte_** (here's the link : [http://www.wowhead.com/spell=205183/secrets-of-the-necrolyte](url) ) 
As damage is increased by 200%, but healing must remain the same, it goes down from 600% of your damage to 198%, when specced to affliction. It remains 600% for the other 2 spec.

What is odd, is the last number you gave, since 198% -> 258% is a 30% increase, and that would probably be the only issue here, still worth an investigation though.

**Comment by Moustachos** [comment]
Ref #5979
