### ISSUE TITLE
Emerald Portals

### ISSUE THREAD

**Issue by Maldazar-Valhalla** [Valhalla-Gaming/Tracker#8123]
Referring to https://github.com/Valhalla-Gaming/Tracker/issues/7446
People are abusing this by bringing low level alts to Broken Isles and grinding eggs in Val'sharah which shouldn't be possible.

**Comment by llamalama** [comment]
They could be using a mage portal to get there instead. Mages can portal players of any level and that is intentional from Blizzard. So really, having low level players there is possible without any bugs. (Although I totally agree, I hate when I see low levels farming the eggs)
http://www.wowhead.com/spell=224871/portal-dalaran-broken-isles

**Comment by Redrian-Valhalla** [comment]
llamalama is correct, there's no bug on teleportation via mage portals, while #7446 is correct too, the problem is about powerleveling in this case and that's an exploit.
