### ISSUE TITLE
Mozzy's Reunion

### ISSUE THREAD

**Issue by nibbyy** [Valhalla-Gaming/Tracker#8225]
UPDATE: Tried abandoning the quest and retrying it, same thing happens, but this time the bird came down. However, I couldn't attack the bird and it just flew away as soon as it came. She's doing the same thing now.

**Describe the issue you're having**:
On the final part of the quest Moozy's Reunion in Highmountain, the part:
'Reunite Ethel Waterwise with Her Family'
She stops moving halfway across the bridge and stays there, meaning the quest can't be completed.

**Explain how you expect it work**:
Ethel should cross the bridge and continue walking to her family.

**Steps to reproduce the problem**:

1.  Begin Moozy's Reunion
2. Reach this final part of it
3. Watch as she doesn't move across the bridge

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/quest=42590

**Comment by Guybrush-VR** [comment]
Anybody else can confirm this issue?

**Comment by VictorTyne** [comment]
I can confirm this issue still exists. Happened to my group today. I was able to complete the quest with no problems, but my friend had Ethel stop in the middle of the bridge after the roc attack.

Abandoning the quest successfully despawned Ethel, but now she can't get the quest again, since abandoning the quest didn't reset the instance and respawn Seela at the cave.
