### ISSUE TITLE
Damage output does not match what is being dealt

### ISSUE THREAD

**Issue by braebrook** [Valhalla-Gaming/Tracker#8321]
**Describe the issue you're having**:
Now that I have started questing in Highmountain I have noticed that the damage numbers showing on the screen do not match the amount of damage being done to the mob.  For example, if I hit a mob for 75,000 their health is only going down 2k or 3k.  It is taking forever to kill a mob.  I am level 101 but I would still think the damage would be the same as I have seen questing from 1-100.

**Explain how you expect it work**:
I would expect that if I hit a mob for 75k that it would really do 75k in damage.

**Steps to reproduce the problem**:

1.   I've attached several mobs and it seems to be happening on regular questing trash, along with special quests where you kill a "mini" boss.
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by braebrook** [comment]
Swam to Azsuna and was the same way with mobs out there, taking forever to kill a single 101 mob.  Damage being dealt seemed like it was only doing half of what it showed on the screen.

**Comment by braebrook** [comment]
Also the quest "Moose on the Loose" it took 15 minutes to kill the Moose that had 6 million health.

**Comment by Tolno** [comment]
I think the problem comes from the scaling.

It's the same problem that leads casters to miss every single spell, because even if the mob is shown to have your level, the game acts as he's 110, so when you're a 101 caster, you hit 1 out 20 spells, and the damage you deal seems low because it doesn't have (for exemple) 140k hp, but 1050k.
But even then, damage is still too low, maybe another reduction due to the high level difference.

Then again, that may not be exact, only devs can figure that out, that's just my humble conclusion to what I've experienced.

**Comment by braebrook** [comment]
That's what I was thinking. Their level shows level 101 but the scaling of the health and damage done by me isn't scaling. Like you just said, most of my prot paladin spells only hit every once in a while.

**Comment by ixodan** [comment]
yes dmg is low specialy for blade justice am lvl 110 it says it does 152k but when i hit it do 62k very low dmg
