### ISSUE TITLE
Consecration aggros many more mobs than it should

### ISSUE THREAD

**Issue by braebrook** [Valhalla-Gaming/Tracker#8345]
**Describe the issue you're having**:
When using consecration it seems like it aggros mobs in other areas.  One of the first quests in Highmountain has you go in a cave and retrieve crystals and kill mobs. There is a follow up where you kill a mini boss in the upper part of that cave. When using consecration on that boss I aggrod mobs from all the way down the ramp.
**Explain how you expect it work**:
Should just be able to aggrobor use on the mob or mobs you are fighting at that time.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by VictorTyne** [comment]
Consecration seems to be suffering from the same bug as a few other spells whereby the taunting range is set to 100 yards even though the range of the visual effect is 8 yards.
I tried testing this a few times; it only seems to happen under certain circumstances.
It doesn't happen if you cast Consecration and just stand there with hostile mobs inside the 100yrd radius. It only happens if you cast while attacking something and/or get attacked by something.
It could be an interaction with Retribution Aura.

**Comment by Moustachos** [comment]
Ref #5979
