### ISSUE TITLE
[Paladin][Protection][Game Breaking issue] Hand of the Protector.

### ISSUE THREAD

**Issue by Hemoglobine-Valhalla** [Valhalla-Gaming/Tracker#8457]
**Describe the issue you're having**:

Currently such spell does heal the paladin tank and it doesn't work that way from what the spell description show also it can do a critic healing and it is stated that it can't do critic healing.

**Explain how you expect it work**:

Calls down the Light to heal a friendly target for 30% of the target's missing health.

**Steps to reproduce the problem**:

1.  Get a paladin protection
2.  Use such talent on yourself
3.  Notice it does heal you and it shouldn't since it is a heal for a Friendly target and not for the pala.

**Links to Wowhead, YouTube, etc**:

http://www.wowhead.com/spell=213652/hand-of-the-protector

**Comment by Mooshii** [comment]
This talent replaces Light of the protector. And you can use it on yourself just like in retail. Your own character is also a friendly-target. Icyveins guide even recommend this talent because it has a lower CD and thus you can heal yourself more often. http://www.icy-veins.com/wow/protection-paladin-pve-tank-spec-builds-talents so being able to use it on yourself is not a bug. The only thing that is wrong is that it can crit (even tho I have never seen it crit on my pala) so after all skill maybe works as it should. Got to test the crit and if it does then fix.

**Comment by Moustachos** [comment]
Works just fine.

See Mooshii's comment for more details about why you can heal yourself with Hand of the Protector and the "can't crit" part works as intended.

**Comment by Moustachos** [comment]
Ref #5979

**Comment by GM-Pyromanic** [comment]
Also here is a screen grab from retail showing the paladin can use the spell as a self heal. (Character belongs to myself in case you was wondering where the screen grab came from.)
![chrome_2017-02-09_12-30-23](https://cloud.githubusercontent.com/assets/20587569/22783554/44c1e41a-eec4-11e6-830a-8379a20cf9af.png)
