### ISSUE TITLE
backdraft

### ISSUE THREAD

**Issue by Traveler-Valhalla** [Valhalla-Gaming/Tracker#8673]
**Describe the issue you're having**:
increases cast time of chaos bolt and incinerate for **way more** then it should making them almost instant cast (below 1 sec cast for sure)
**Explain how you expect it work**:
"Casting Conflagrate reduces the cast time of your next two Incinerates or Chaos Bolts by 30%."
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=117828/backdraft

**Comment by Uncool1** [comment]
1 Conflagrate gives u 2 charges of Backdrafts which means u can spend these two for 2 Incinerates or 1 Chaos Bolt...... BUT: Warlock can cast 2 Conflagrates which means it gives 4 charges of Backdraft (because they can stack) which also means 2 Chaos Bolts (ofc if u have atleast 4 soul shards cuz 1chaos bolt consumes 2 soul shards). The cast time can be also reduced by Reverse Entropy by additional 0.5 sec.

Conclusion:
It works fine

**Comment by Traveler-Valhalla** [comment]
thats rly strange cuz i was able to cast 4 incinerates 4 times in 1 second without any global cooldown

**Comment by Uncool1** [comment]
1conflagrate = 2backdrafts = 30% cast time reduction
2conflagrate = 4backdrafts = 60% cast time reduction

**Comment by Uncool1** [comment]
Okay now i got a new conclusion ( i have a chance to redeem myself ;p) and its quite simple: backdraft can stack the amount of charges but shouldn't stack cast time reduction which means it should always be the same: 30%

Besides... along with the talent Reverse Entropy ch.bolt cast time can be reduced to 1,2-1,5 sec which is still pretty fast
