### ISSUE TITLE
[Monk][Brewmaster] Stagger not reducing damage properly

### ISSUE THREAD

**Issue by Analog-Valhalla** [Valhalla-Gaming/Tracker#9252]
**Describe the issue you're having**:
Stagger reduces about 2 times as much physical damage than it should. This results in about 80-85% physical damage mitigation that can be easily reduced by Purifying Brew, essentially allows the monk to absorb 80% physical damage at all times with ease (Works perfect for magic damage reduction). This is an Issue for PvE and PvP. Another issue that occurs is that stagger does not deal the ticking damage over time properly to the caster. At high stagger numbers close to or larger than the user's health the damage done every 0.5 seconds is not even close to correct, also there is no damage done to the user in certain intervals. This should not be the case. 
**Explain how you expect it work**:
Mitigate 40% of Physical damage, taking it over 10 sec. Take damage from the stagger debuff equivalent to the tooltip's calcuations, also take damage from stagger every 0.5 seconds while having the debuff.
**Steps to reproduce the problem**:

1. Pull a ton of Mobs
2. Let the stagger grow to as much as you want
3. Stay invincible

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=124255/stagger
<a href="http://imgur.com/R2ctwZF"><img src="http://i.imgur.com/R2ctwZF.jpg" title="source: imgur.com" /></a>
<a href="http://imgur.com/yruZhCA"><img src="http://i.imgur.com/yruZhCA.jpg" title="source: imgur.com" /></a>
<a href="http://imgur.com/jI0mkqC"><img src="http://i.imgur.com/jI0mkqC.jpg" title="source: imgur.com" /></a>
<a href="http://imgur.com/zLr4FhD"><img src="http://i.imgur.com/zLr4FhD.jpg" title="source: imgur.com" /></a>

**Comment by Nightcap** [comment]
I'm not sure if your deduction included the brewmaster spells and abilities that increase stagger duration and stagger from magic. I'll link them below and you can tell me if they are accounted for or not.

Ironskin Brew
Instant	21 sec recharge
3 Charges
Requires Monk (Brewmaster)
Requires level 20
Increases the damage you delay with Stagger by an additional 40% for 6 sec. 

Shares charges with Purifying Brew.

Mystic Vitality - Increases our ability to stagger magic damage by 40%. Do note this is not an additive 40% and its additive value is relative to the
amount of stagger you have.

High Tolerance - Increases base stagger by 10% as well as providing a haste buff that provides a relative amount of haste depending on the
severity of your stagger pool; 5% for light stagger 10% for medium stagger, and 15% for heavy stagger.

Fortifying Brew - Reduces damage taken and increases your max health and stagger by 20% for 15 seconds. 7 minute cooldown.

http://www.wowhead.com/brewmaster-talent-guide

These are all powerful when used in combination and at the right times ofc, but all are limited to CD's and or being used at the proper times. I would not call it invincible by any means, very strong when played correctly though, for sure.

**Comment by SL-Starcaller** [comment]
Anything we can do considering the people purposely abusing this in BGs?

**Comment by Analog-Valhalla** [comment]
Hello there, 
I am very familiar of how testing the abilities work. I had no talents selected other than Gift of the Mists, Leg sweep, and Black Out Combo. During this test the only abilities used were Purifying brew every 1 1/2 minutes and Effuse.
Do not worry about incorrect testing. These numbers are from my self, with a video included for the developers. I understand your concern for this spec, but unfortunately an issue like this cannot be over looked. 
Thank you,
Analog :D

**Comment by Nightcap** [comment]
Ok, well just so you know, iron skin which should be up almost all the time should account for 80% stagger by itself, its the main mitigation tool. So if you never used it I recommend putting it in your rotation.

**Comment by Analog-Valhalla** [comment]
Iron Skin was not used in these tests. Using Iron skin + The current Stagger amount results in 120% physical damage mitigation, essentially all damage taken. This is not how it was intended. Thank you

**Comment by alucula** [comment]
Hello Nightcap I was looking at this post meanwhile thinking that I should lvl up my monk but Analog said that the spell called "stagger" isn't working why did you reply with all this monk brew guide ? :P
Anyway nice to see activity here and to see so much detail

**Comment by Nightcap** [comment]
@alucula  This isn't a forum, please don't jump in to start a conversation within a conversation. We are on the tracker to figure out problems with scripting.

@Analog Please forgive me, You seem to have taken my inquiry on your post as questioning your ability to test and or be credible, that wasn't my intention. I'm just trying to figure out and help the issue post along.

Initially, You spoke of stagger not adding up properly, But there's so many variables with stagger that it confuses almost everyone who tries to understand it initially. Since these things were not ruled out at the start of the post, I listed them and asked if they were considered or not. And the images don't show any stagger interactions clearly, just the damage causes, is why I had to ask.

That said, if there are stagger inconsistencies, I haven't noticed them. But I have noticed that Stagger seems to drop suddenly since the last update, after it's gotten over 100% as you mentioned. Since stagger % is based on the BrM's current, not over all HP%, this can be very tricky to notice or track accurately. 

And just to clear up one point, no amount of stagger can make you invincible, You still take all the damage, just at a slower rate than others do. Which is also largely limited once Iron skin brew and Black ox brew are on CD at the same time.

I'm not saying stagger is working 100% correctly, just that if it isn't, that it is not enough to be noticeable by me or any trackers I can find that are reliable for stagger logs. This is why no one can Sim Stagger very accurately in any given situation.

-With respect, Nightcap

**Comment by Analog-Valhalla** [comment]
@Nightcap Thank you for you interest on this topic. I will not go into much detail or take any more of your time, but the problem has been identified, and will be fixed.

**Comment by theprototyze** [comment]
Trying to save your only moments of glory from being balanced properly is not a nice thing to do. Not sure how and why only the brewmasters seem to do this on the tracker.

**Comment by Nightcap** [comment]
@theprototyze  Whatever that means. Stop following me around and commenting on everything I'm involved in. It's really annoying.

**Comment by Analog-Valhalla** [comment]
Comment snipped. Please do any disputes privately.  @Nightcap " This isn't a forum" The Issue tracker is meant for class, and wow mechanic related issues, not personal ones. If there is an issue with correcting exploits and incorrect game mechanics please message me privately via the forum and we can discuss this further. Until then please do not respond on this thread unless it incorporates issues that were missed or overlooked. Thank you.
